/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_ipc.views;
import java.io.IOException;
import javax.swing.JOptionPane;
import proyecto1_ipc.controllers.ProductoController;
/**
 *
 * @author ixche
 */
public class VistaRegistrar extends javax.swing.JFrame {
    private ProductoController controller;
    private VistaPrincipal menu;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaRegistrar.class.getName());

    /**
     * Creates new form VistaRegistrar
     */
public VistaRegistrar(VistaPrincipal menu, ProductoController controller) {
    initComponents();
    this.menu = menu;
    this.controller = controller;
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        RegistroVenta = new javax.swing.JLabel();
        codigoProd = new javax.swing.JLabel();
        txtcodProd = new javax.swing.JTextField();
        CantidadVenta = new javax.swing.JLabel();
        txtCantidadVenta = new javax.swing.JTextField();
        BotRegistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 200, 250));

        RegistroVenta.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        RegistroVenta.setText("Registrar venta");

        codigoProd.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        codigoProd.setText("Código del producto");

        txtcodProd.setBackground(new java.awt.Color(255, 204, 204));

        CantidadVenta.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        CantidadVenta.setText("Cantidad vendida");

        txtCantidadVenta.setBackground(new java.awt.Color(255, 204, 204));

        BotRegistrar.setBackground(new java.awt.Color(255, 153, 153));
        BotRegistrar.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        BotRegistrar.setText("Registrar");
        BotRegistrar.addActionListener(this::BotRegistrarActionPerformed);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CantidadVenta)
                        .addGap(0, 162, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCantidadVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(codigoProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodProd, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(59, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegistroVenta)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistroVenta)
                .addGap(18, 18, 18)
                .addComponent(codigoProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CantidadVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRegistrarActionPerformed

        int id = Integer.parseInt(txtcodProd.getText());
        int cantidad = Integer.parseInt(txtCantidadVenta.getText());

        String resultado = null;
        try {
            resultado = controller.registrarVenta(id, cantidad);
        } catch (IOException ex) {
            System.getLogger(VistaRegistrar.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        JOptionPane.showMessageDialog(this, resultado);
    }//GEN-LAST:event_BotRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotRegistrar;
    private javax.swing.JLabel CantidadVenta;
    private javax.swing.JLabel RegistroVenta;
    private javax.swing.JLabel codigoProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtcodProd;
    // End of variables declaration//GEN-END:variables
}
