/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_ipc.views;

/**
 *
 * @author ixche
 */
public class VistaBuscarCategoria extends javax.swing.JFrame {
     private VistaPrincipal menu;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaBuscarCategoria.class.getName());

    /**
     * Creates new form VistaBuscarCategoria
     */
    public VistaBuscarCategoria() {
        initComponents();
    }
    
      VistaBuscarCategoria(VistaPrincipal menu) {
    initComponents();
    this.menu = menu;
    setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BuscarCat = new javax.swing.JLabel();
        txtCategoriaaBuscar = new javax.swing.JTextField();
        txtBusCat = new javax.swing.JButton();
        txtCerrarBuscarCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        BuscarCat.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BuscarCat.setText("Escriba la categoría que desea buscar");

        txtBusCat.setBackground(new java.awt.Color(255, 153, 153));
        txtBusCat.setText("Buscar");
        txtBusCat.addActionListener(this::txtBusCatActionPerformed);

        txtCerrarBuscarCat.setBackground(new java.awt.Color(255, 153, 153));
        txtCerrarBuscarCat.setText("Cerrar");
        txtCerrarBuscarCat.addActionListener(this::txtCerrarBuscarCatActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BuscarCat)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtCategoriaaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCerrarBuscarCat)
                            .addComponent(txtBusCat))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BuscarCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCategoriaaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCerrarBuscarCat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusCatActionPerformed

    private void txtCerrarBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCerrarBuscarCatActionPerformed
            menu.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_txtCerrarBuscarCatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarCat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txtBusCat;
    private javax.swing.JTextField txtCategoriaaBuscar;
    private javax.swing.JButton txtCerrarBuscarCat;
    // End of variables declaration//GEN-END:variables
}
