/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_ipc.views;

/**
 *
 * @author ixche
 */
public class VistaAgregar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAgregar.class.getName());
  
    /**
     * Creates new form VistaAgregar
     */
    public VistaAgregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agProd = new javax.swing.JLabel();
        NombreProd = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        Categoria = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JTextField();
        Precio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        CantidadStock = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 206, 255));

        agProd.setBackground(new java.awt.Color(204, 255, 255));
        agProd.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        agProd.setText("Agregar Producto");

        NombreProd.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        NombreProd.setText("Nombre del producto");

        txtNombre.setBackground(new java.awt.Color(255, 204, 204));
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        Categoria.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Categoria.setText("Categoría");

        txtcategoria.setBackground(new java.awt.Color(255, 204, 204));

        Precio.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Precio.setText("Precio");

        txtPrecio.setBackground(new java.awt.Color(255, 204, 204));

        CantidadStock.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        CantidadStock.setText("Cantidad en Stock");

        txtcantidad.setBackground(new java.awt.Color(255, 204, 204));

        id.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        id.setText("Id");

        txtId.setBackground(new java.awt.Color(255, 204, 204));

        txtAgregar.setBackground(new java.awt.Color(255, 153, 153));
        txtAgregar.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        txtAgregar.setText("Agregar");

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAgregar)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreProd)
                    .addComponent(Categoria)
                    .addComponent(Precio)
                    .addComponent(CantidadStock)
                    .addComponent(jButton1)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(txtPrecio)
                    .addComponent(txtcategoria)
                    .addComponent(txtNombre)
                    .addComponent(txtId))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agProd)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(agProd)
                .addGap(18, 18, 18)
                .addComponent(NombreProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Precio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CantidadStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantidadStock;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel NombreProd;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel agProd;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txtAgregar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcategoria;
    // End of variables declaration//GEN-END:variables
}
