/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_ipc.views;

import Singleton.SingletonId;
import java.io.IOException;
import proyecto1_ipc.controllers.ProductoController;

/**
 *
 * @author ixche
 */
public class VistaReportes extends javax.swing.JFrame {
     private VistaPrincipal menu;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaReportes.class.getName());

        ProductoController prodController=new ProductoController();
        SingletonId singleton = new SingletonId();
        
  public VistaReportes(VistaPrincipal menu){
      initComponents();
    this.menu = menu;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reportes = new javax.swing.JLabel();
        btnHTML = new javax.swing.JButton();
        btnReporteVentas = new javax.swing.JButton();
        btnCerrarVReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 195, 255));

        reportes.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        reportes.setText("Reportes");

        btnHTML.setBackground(new java.awt.Color(255, 153, 153));
        btnHTML.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        btnHTML.setText("Ver reporte de Stock");
        btnHTML.addActionListener(this::btnHTMLActionPerformed);

        btnReporteVentas.setBackground(new java.awt.Color(255, 153, 153));
        btnReporteVentas.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        btnReporteVentas.setText("Ver reporte de Ventas");

        btnCerrarVReportes.setBackground(new java.awt.Color(255, 153, 153));
        btnCerrarVReportes.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        btnCerrarVReportes.setText("Cerrar");
        btnCerrarVReportes.addActionListener(this::btnCerrarVReportesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(reportes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReporteVentas)
                            .addComponent(btnHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnCerrarVReportes)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportes)
                .addGap(18, 18, 18)
                .addComponent(btnHTML)
                .addGap(18, 18, 18)
                .addComponent(btnReporteVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarVReportes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHTMLActionPerformed
         try {
             ProductoController.generarHTML();
         } catch (IOException ex) {
             ex.printStackTrace();
         }
    }//GEN-LAST:event_btnHTMLActionPerformed

    private void btnCerrarVReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarVReportesActionPerformed
           menu.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnCerrarVReportesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarVReportes;
    private javax.swing.JButton btnHTML;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel reportes;
    // End of variables declaration//GEN-END:variables
}
