/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_ipc.views;
import proyecto1_ipc.controllers.ProductoController;

/**
 *
 * @author ixche
 */
public class VistaPrincipal extends javax.swing.JFrame {
  
    
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());
   private ProductoController controller = new ProductoController();
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuprincipal = new javax.swing.JLabel();
        opc = new javax.swing.JLabel();
        AgregarProducto = new javax.swing.JButton();
        BuscarProducto = new javax.swing.JButton();
        EliminarProducto = new javax.swing.JButton();
        RegistrarVenta = new javax.swing.JButton();
        GenerarReportes = new javax.swing.JButton();
        DatosEstudiante = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        menuprincipal.setBackground(new java.awt.Color(255, 204, 255));
        menuprincipal.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuprincipal.setText("Bienvenido al menu principal");
        menuprincipal.setToolTipText("");

        opc.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        opc.setText("Elija una opcion");

        AgregarProducto.setBackground(new java.awt.Color(255, 204, 255));
        AgregarProducto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        AgregarProducto.setText("Agregar producto");
        AgregarProducto.addActionListener(this::AgregarProductoActionPerformed);

        BuscarProducto.setBackground(new java.awt.Color(255, 204, 255));
        BuscarProducto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        BuscarProducto.setText("Buscar producto");
        BuscarProducto.addActionListener(this::BuscarProductoActionPerformed);

        EliminarProducto.setBackground(new java.awt.Color(255, 204, 255));
        EliminarProducto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        EliminarProducto.setText("Eliminar producto");
        EliminarProducto.addActionListener(this::EliminarProductoActionPerformed);

        RegistrarVenta.setBackground(new java.awt.Color(255, 204, 255));
        RegistrarVenta.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        RegistrarVenta.setText("Registrar venta");
        RegistrarVenta.addActionListener(this::RegistrarVentaActionPerformed);

        GenerarReportes.setBackground(new java.awt.Color(255, 204, 255));
        GenerarReportes.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        GenerarReportes.setText("Generar reportes");
        GenerarReportes.addActionListener(this::GenerarReportesActionPerformed);

        DatosEstudiante.setBackground(new java.awt.Color(255, 204, 255));
        DatosEstudiante.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        DatosEstudiante.setText("Ver datos del estudiante");
        DatosEstudiante.addActionListener(this::DatosEstudianteActionPerformed);

        Salir.setBackground(new java.awt.Color(255, 204, 255));
        Salir.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Salir.setText("Salir      ");
        Salir.addActionListener(this::SalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarProducto)
                    .addComponent(opc)
                    .addComponent(BuscarProducto)
                    .addComponent(EliminarProducto)
                    .addComponent(RegistrarVenta)
                    .addComponent(GenerarReportes)
                    .addComponent(DatosEstudiante)
                    .addComponent(Salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(menuprincipal)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(menuprincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AgregarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenerarReportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatosEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salir)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProductoActionPerformed
        VistaBuscar vBuscar=new VistaBuscar(this); 
        vBuscar.setVisible(true);
        vBuscar.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BuscarProductoActionPerformed

    private void EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoActionPerformed
        VistaEliminar vEliminar=new VistaEliminar(this);
        vEliminar.setVisible(true);
        vEliminar.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_EliminarProductoActionPerformed
    

    private void GenerarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarReportesActionPerformed
     VistaReportes vReportes = new VistaReportes(this, controller);
      vReportes.setVisible(true);
      vReportes.setLocationRelativeTo(null);
      this.setVisible(false);
        
    }//GEN-LAST:event_GenerarReportesActionPerformed

    private void DatosEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosEstudianteActionPerformed
        
        VistaDatosEstudiante vEstudiante=new VistaDatosEstudiante(this); 
        vEstudiante.setVisible(true);
        this.setVisible(false);
        vEstudiante.setLocationRelativeTo(null);
    }//GEN-LAST:event_DatosEstudianteActionPerformed

    private void AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoActionPerformed
         VistaAgregar vAgregar=new VistaAgregar(this);
      vAgregar.setVisible(true);
      vAgregar.setLocationRelativeTo(null);
      this.setVisible(false);
    }//GEN-LAST:event_AgregarProductoActionPerformed

    private void RegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarVentaActionPerformed
        
    VistaRegistrar v = new VistaRegistrar(this, controller);
     v.setVisible(true);
     v.setLocationRelativeTo(null);
     this.dispose();
       
    }//GEN-LAST:event_RegistrarVentaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarProducto;
    private javax.swing.JButton BuscarProducto;
    private javax.swing.JButton DatosEstudiante;
    private javax.swing.JButton EliminarProducto;
    private javax.swing.JButton GenerarReportes;
    private javax.swing.JButton RegistrarVenta;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menuprincipal;
    private javax.swing.JLabel opc;
    // End of variables declaration//GEN-END:variables
}
